### 01. Pandas version

In [ ]:
import pandas as pd

pd.__version__

'2.3.0'

### Getting the data
(this loads the data to the repository root)

In [8]:
!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv

--2025-06-19 11:15:14--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/laptops.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 2606:50c0:8001::154, 2606:50c0:8000::154, 2606:50c0:8003::154, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|2606:50c0:8001::154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 298573 (292K) [text/plain]
Saving to: ‘laptops.csv’

laptops.csv         100%[===================>] 291,58K  --.-KB/s    in 0,07s   

2025-06-19 11:15:15 (4,01 MB/s) - ‘laptops.csv’ saved [298573/298573]



In [ ]:
df = pd.read_csv("laptops.csv")

### Q2
How many records are in the dataset?

In [11]:
len(df)

2160

### Q3. Laptop brands
How many laptop brands are presented in the dataset?

In [14]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [ ]:
df["Brand"].nunique()

27

### Q4. Missing values
How many columns in the dataset have missing values?

In [24]:
df.isnull()

Laptop  Status  Brand  Model    CPU    RAM  Storage  Storage type  \
0      False   False  False  False  False  False    False         False   
1      False   False  False  False  False  False    False         False   
2      False   False  False  False  False  False    False         False   
3      False   False  False  False  False  False    False         False   
4      False   False  False  False  False  False    False         False   
...      ...     ...    ...    ...    ...    ...      ...           ...   
2155   False   False  False  False  False  False    False         False   
2156   False   False  False  False  False  False    False         False   
2157   False   False  False  False  False  False    False         False   
2158   False   False  False  False  False  False    False         False   
2159   False   False  False  False  False  False    False         False   

        GPU  Screen  Touch  Final Price  
0      True   False  False        False  
1      True   False  False        False  
2      True   False  False        False  
3     False   False  False        False  
4      True   False  False        False  
...     ...     ...    ...          ...  
2155  False   False  False        False  
2156  False   False  False        False  
2157  False   False  False        False  
2158   True   False  False        False  
2159   True   False  False        False  

[2160 rows x 12 columns]

In [25]:
df.isnull().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen           True
Touch           False
Final Price     False
dtype: bool

In [26]:
df.isnull().any().sum()

np.int64(3)

### Q5. Maximum final price
What's the maximum final price of Dell notebooks in the dataset?

In [28]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [ ]:
df[df["Brand"].str.lower() == "dell"].head()

Laptop Status Brand     Model  \
161  Dell Vostro 3510 Intel Core i3-1115G4/8 GB/256...    New  Dell    Vostro   
271  Dell Vostro 3510 Intel Core i5-1135G7/8 GB/256...    New  Dell    Vostro   
281  Dell Vostro 3520 Intel Core i7-1255U/16GB/512G...    New  Dell    Vostro   
319  Dell Latitude 3520 Intel Core i5-1135G7/8GB/25...    New  Dell  Latitude   
328  Dell Vostro 3510 Intel Core i5-1135G7/16 GB/51...    New  Dell    Vostro   

               CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
161  Intel Core i3    8      256          SSD  NaN    15.6    No       599.00  
271  Intel Core i5    8      256          SSD  NaN    15.6    No       690.15  
281  Intel Core i7   16      512          SSD  NaN    15.6    No       889.00  
319  Intel Core i5    8      256          SSD  NaN    15.6    No       789.00  
328  Intel Core i5   16      512          SSD  NaN    15.6    No       869.00

In [ ]:
df[df["Brand"].str.lower() == "dell"]["Final Price"].max()

np.float64(3936.0)

### Q6. Median value of Screen

1. Find the median value of `Screen` column in the dataset.
2. Next, calculate the most frequent value of the same `Screen` column.
3. Use `fillna` method to fill the missing values in `Screen` column with the most frequent value from the previous step.
4. Now, calculate the median value of `Screen` once again.

Has it changed?

> Hint: refer to existing `mode` and `median` functions to complete the task.

- Yes
- No

In [ ]:
original_median = df["Screen"].median()
original_median

np.float64(15.6)

In [ ]:
df["Screen"].mode()

0    15.6
Name: Screen, dtype: float64

In [ ]:
mode_value = df["Screen"].mode()[0]
df["Screen"] = df["Screen"].fillna(mode_value)
df.isnull().any()

Laptop          False
Status          False
Brand           False
Model           False
CPU             False
RAM             False
Storage         False
Storage type     True
GPU              True
Screen          False
Touch           False
Final Price     False
dtype: bool

In [ ]:
df["Screen"].median()

np.float64(15.6)

### Q7. Sum of weights

1. Select all the "Innjoo" laptops from the dataset.
2. Select only columns `RAM`, `Storage`, `Screen`.
3. Get the underlying NumPy array. Let's call it `X`.
4. Compute matrix-matrix multiplication between the transpose of `X` and `X`. To get the transpose, use `X.T`. Let's call the result `XTX`.
5. Compute the inverse of `XTX`.
6. Create an array `y` with values `[1100, 1300, 800, 900, 1000, 1100]`.
7. Multiply the inverse of `XTX` with the transpose of `X`, and then multiply the result by `y`. Call the result `w`.
8. What's the sum of all the elements of the result?

> **Note**: You just implemented linear regression. We'll talk about it in the next lesson.

In [ ]:
df[df["Brand"] == "Innjoo"]

Laptop Status   Brand Model  \
1478  InnJoo Voom Excellence Intel Celeron N4020/8GB...    New  Innjoo  Voom   
1479  InnJoo Voom Excellence Pro Intel Celeron N4020...    New  Innjoo  Voom   
1480  Innjoo Voom Intel Celeron N3350/4GB/64GB eMMC/...    New  Innjoo  Voom   
1481  Innjoo Voom Laptop Max Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1482  Innjoo Voom Laptop Pro Intel Celeron N3350/6GB...    New  Innjoo  Voom   
1483  Innjoo Voom Pro Intel Celeron N3350/6GB/128GB ...    New  Innjoo  Voom   

                CPU  RAM  Storage Storage type  GPU  Screen Touch  Final Price  
1478  Intel Celeron    8      256          SSD  NaN    15.6    No       311.37  
1479  Intel Celeron    8      512          SSD  NaN    15.6    No       392.55  
1480  Intel Celeron    4       64         eMMC  NaN    14.1    No       251.40  
1481  Intel Celeron    6       64         eMMC  NaN    14.1    No       383.61  
1482  Intel Celeron    6      128          SSD  NaN    14.1    No       317.02  
1483  Intel Celeron    6      128         eMMC  NaN    14.1    No       431.38

In [ ]:
df[df["Brand"] == "Innjoo"][["RAM", "Storage", "Screen"]]

RAM  Storage  Screen
1478    8      256    15.6
1479    8      512    15.6
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [ ]:
X = df[df["Brand"] == "Innjoo"][["RAM", "Storage", "Screen"]].to_numpy()
X

array([[  8. , 256. ,  15.6],
       [  8. , 512. ,  15.6],
       [  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [89]:
XTX = (X.T).dot(X)
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [ ]:
import numpy as np

XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [91]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [92]:
w = XTX_inv.dot(X.T).dot(y)
w

array([45.58076606,  0.42783519, 45.29127938])

In [93]:
w.sum()

np.float64(91.2998806299555)